// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVWHjxEu6r-G40EvN1HQt6N_AoaUl6Unc',
    appId: '1:659085098166:android:1f0ec9a7319550484b3a17',
    messagingSenderId: '659085098166',
    projectId: 'patgolito-6f54e',
    storageBucket: 'patgolito-6f54e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClUplJWgdK_780XItYpwCbpTvdXlfjpMw',
    appId: '1:659085098166:ios:d7c84ef8b3164d5d4b3a17',
    messagingSenderId: '659085098166',
    projectId: 'patgolito-6f54e',
    storageBucket: 'patgolito-6f54e.firebasestorage.app',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClUplJWgdK_780XItYpwCbpTvdXlfjpMw',
    appId: '1:659085098166:ios:d7c84ef8b3164d5d4b3a17',
    messagingSenderId: '659085098166',
    projectId: 'patgolito-6f54e',
    storageBucket: 'patgolito-6f54e.firebasestorage.app',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLC65LU8fRHUPlOep7mx-7_wf6fM-bTYM',
    appId: '1:659085098166:web:fdaec6f6cc0f45e34b3a17',
    messagingSenderId: '659085098166',
    projectId: 'patgolito-6f54e',
    authDomain: 'patgolito-6f54e.firebaseapp.com',
    storageBucket: 'patgolito-6f54e.firebasestorage.app',
    measurementId: 'G-W1RQ7ZDG35',
  );
}
